const langEN = {
    "ABOUT_ME": "ABOUT ME",
    "ABOUT_ME_DESC": "I am a Full-Stack Software Developer specializing in data-driven application engineering. My last three years have been dedicated to crafting end-to-end solutions, building dynamic user interfaces with React/TypeScript and scalable services with Python. I hold hands-on expertise in industrial data modeling and API integration using Cognite Data Fusion (FDM), complemented by strong skills in SQL, Docker, and Azure DevOps.",
    "MAIN_QUALIFICATIONS": "MAIN QUALIFICATIONS",
    "PROFESSIONAL_EXPERIENCE": "PROFESSIONAL EXPERIENCE",
    "COMPANY_RADIX": "RADIX – Engineering and Software",
    "JOB_SPEC_1": "Specialist I - Developer | ",
    "DATE_FEB_26": "Feb 2026 – Present",
    "JOB_SENIOR": "Senior Developer | ",
    "DATE_NOV_23": "Nov 2023 – Jan 2026",
    "ACTIVITIES_HEADING": "Activities:",
    "ACT_RADIX_1": "Design and implement data modeling in Cognite Fusion Data Model (FDM)",
    "ACT_RADIX_2": "Development of REST API endpoints using Cognite Python SDK.",
    "ACT_RADIX_3": "Creation of a dynamic and responsive user interface using React.js",
    "ACT_RADIX_4": "Collaborated with Business Analysts to assess the feasibility of proposed solutions and address project requirements.",
    "ACT_RADIX_5": "Development of REST API with NestJS",
    "ACT_RADIX_6": "Development of mobile screens using React Native",
    "ACT_RADIX_7": "Accelerated delivery with AI assisted IDE (Cursor)",
    "MAIN_PROJECTS_HEADING": "Main Projects:",
    "PROJ_1": "Celanese - Digitization project",
    "PROJ_2": "Radix – JO/AI",
    "PROJ_3": "Featbank – web app and mobile app",
    "COMPANY_ANP": "ANP - National Agency of Petroleum, Natural Gas and Biofuels",
    "JOB_RESEARCHER": "Researcher | ",
    "DATE_JUN_20": "Jun 2020 – Jul 2022",
    "ACT_ANP_1": "Survey of the state of the art on Reinforcement Learning (RL) applied to systems control;",
    "ACT_ANP_2": "Proposition of a reward architecture for the agent/controller applicable to the artificial elevation of oil and gas by Electric Submersible Pumps (ESP);",
    "ACT_ANP_3": "Implementation of the advanced control systems in the ESP oil lifting pilot plant using MATLAB/Simulink.",
    "COMPANY_KLABIN": "KLABIN – Pulp and Paper",
    "JOB_AUTO": "Automation Technical Assistant | ",
    "DATE_JUL_18": "Jul 2018 - Aug 2022",
    "ACT_KLA_1": "Act in the creation of solutions aimed at monitoring the production process, quality maintenance and failure prevention, through the unit's tools (PI System; Excel and Power BI).",
    "ACT_KLA_2": "Carry out the monitoring of the main displays of information, support facilitators in the area in resolving difficulties with created systems.",
    "ACT_KLA_3": "Be the facilitator of the unit's OEE system, ensuring good operation.",
    "ACT_KLA_4": "Responsible for the unit's PI System in the implementation of new demands, maintenance of the base conditions of the system (Software and Hardware) and needs for updates and/or upgrades.",
    "ACT_KLA_5": "Ensure with the automation team the correct application and integration of systems.",
    "ACADEMIC_BACKGROUND": "ACADEMIC BACKGROUND",
    "EDU_1": "Master’s degree in Systems Engineering – University of São Paulo, Brazil – 2025 (in progress)",
    "EDU_2": "MBA in Industrial Automation | USP, Brazil – 2020",
    "EDU_3": "Post Graduation in Control and Automation Engineering | Mauá Institute of Technology, Brazil – 2016",
    "EDU_4": "Bachelor of Automation and Control Engineering | Universidade Federal da Bahia (UFBA), Brazil – 2010",
    "EDU_5": "Technical course in electromechanics | Instituto Federal da Bahia (IFBA), Brazil - 2004",
    "CERTIFICATIONS": "CERTIFICATIONS",
    "CERT_1": "Process Kaizen Engineering – Maintenance",
    "CERT_2": "Process Kaizen Engineering – Quality",
    "CERT_3": "PI System Infrastructure Specialist",
    "CERT_4": "PI System Installation Specialist",
    "CERT_5": "AWS Cloud Practitioner",
    "CERT_6": "MiniTab Certificate",
    "AWARDS_AND_PUBLICATIONS": "AWARDS AND PUBLICATIONS",
    "AWARDS_1": "Technip’s “Jacques Franquelin” Award at the Innovation Global Contest, in 2013: “YouTube for Engineering”",
    "LANGUAGES": "LANGUAGES",
    "LANG_1": "Portuguese – Native",
    "LANG_2": "English – Fluent",
    "LANG_3": "Spanish – Upper Intermediate"
};
