const langPT = {
    "ABOUT_ME": "SOBRE MIM",
    "ABOUT_ME_DESC": "Sou um Desenvolvedor de Software Full-Stack especializado em engenharia de aplicações web usando dados. Meus últimos três anos foram dedicados à criação de soluções de ponta a ponta, construindo interfaces de usuário dinâmicas com React/TypeScript e serviços escaláveis com Python. Tenho experiência prática em modelagem de dados industriais e integração de API usando Cognite Data Fusion (FDM), complementada por fortes habilidades em SQL, Docker e Azure DevOps.",
    "MAIN_QUALIFICATIONS": "PRINCIPAIS QUALIFICAÇÕES",
    "PROFESSIONAL_EXPERIENCE": "EXPERIÊNCIA PROFISSIONAL",
    "COMPANY_RADIX": "RADIX – Engenharia e Software",
    "JOB_SPEC_1": "Especialista I - Desenvolvedor | ",
    "DATE_FEB_26": "Fev 2026 – Presente",
    "JOB_SENIOR": "Desenvolvedor Sênior | ",
    "DATE_NOV_23": "Nov 2023 – Jan 2026",
    "ACTIVITIES_HEADING": "Atividades:",
    "ACT_RADIX_1": "Projetar e implementar modelagem de dados no Cognite Fusion Data Model (FDM)",
    "ACT_RADIX_2": "Desenvolvimento de endpoints de API REST usando Cognite Python SDK.",
    "ACT_RADIX_3": "Criação de interface de usuário dinâmica e responsiva usando React.js",
    "ACT_RADIX_4": "Colaborei com Analistas de Negócios para avaliar a viabilidade das soluções propostas e atender aos requisitos do projeto.",
    "ACT_RADIX_5": "Desenvolvimento de API REST com NestJS",
    "ACT_RADIX_6": "Desenvolvimento de telas mobile usando React Native",
    "ACT_RADIX_7": "Aceleração de entrega com IDE auxiliada por IA (Cursor)",
    "MAIN_PROJECTS_HEADING": "Principais Projetos:",
    "PROJ_1": "Celanese - Projeto de digitalização",
    "PROJ_2": "Radix – JO/AI",
    "PROJ_3": "Featbank – web app e aplicativo mobile",
    "COMPANY_ANP": "ANP - Agência Nacional do Petróleo, Gás Natural e Biocombustíveis",
    "JOB_RESEARCHER": "Pesquisador | ",
    "DATE_JUN_20": "Jun 2020 – Jul 2022",
    "ACT_ANP_1": "Pesquisa do estado da arte sobre Aprendizado por Reforço (RL) aplicado ao controle de sistemas;",
    "ACT_ANP_2": "Proposição de uma arquitetura de recompensa para o agente/controlador aplicável à elevação artificial de óleo e gás por Bombas Submersíveis Elétricas (BCS);",
    "ACT_ANP_3": "Implementação dos sistemas avançados de controle na planta piloto de elevação de petróleo BCS usando MATLAB/Simulink.",
    "COMPANY_KLABIN": "KLABIN – Celulose e Papel",
    "JOB_AUTO": "Assistente Técnico de Automação | ",
    "DATE_JUL_18": "Jul 2018 - Ago 2022",
    "ACT_KLA_1": "Atuar na criação de soluções voltadas para o monitoramento do processo produtivo, manutenção da qualidade e prevenção de falhas, através das ferramentas da unidade (PI System, Excel e Power BI).",
    "ACT_KLA_2": "Realizar o monitoramento dos principais painéis de indicadores, apoiar facilitadores da área na resolução de dificuldades com sistemas criados.",
    "ACT_KLA_3": "Ser o facilitador do sistema OEE da unidade, garantindo sua boa operação.",
    "ACT_KLA_4": "Responsável pelo PI System da unidade na implementação de novas demandas, manutenção das condições base do sistema (Software e Hardware) e necessidades de atualizações e/ou upgrades.",
    "ACT_KLA_5": "Assegurar junto à equipe de automação a correta aplicação e integração dos sistemas.",
    "ACADEMIC_BACKGROUND": "FORMAÇÃO ACADÊMICA",
    "EDU_1": "Mestrado em Engenharia de Sistemas – Universidade de São Paulo, Brasil – 2025 (em andamento)",
    "EDU_2": "MBA em Automação Industrial | USP, Brasil – 2020",
    "EDU_3": "Pós-graduação em Engenharia de Controle e Automação | Instituto Mauá de Tecnologia, Brasil – 2016",
    "EDU_4": "Bacharelado em Engenharia de Controle e Automação | Universidade Federal da Bahia (UFBA), Brasil – 2010",
    "EDU_5": "Curso técnico em eletromecânica | Instituto Federal da Bahia (IFBA), Brasil - 2004",
    "CERTIFICATIONS": "CERTIFICAÇÕES",
    "CERT_1": "Processo de Engenharia Kaizen – Manutenção",
    "CERT_2": "Processo de Engenharia Kaizen – Qualidade",
    "CERT_3": "Especialista em Infraestrutura PI System",
    "CERT_4": "Especialista em Instalação PI System",
    "CERT_5": "AWS Cloud Practitioner",
    "CERT_6": "MiniTab Certificate",
    "AWARDS_AND_PUBLICATIONS": "PRÊMIOS E PUBLICAÇÕES",
    "AWARDS_1": "Prêmio “Jacques Franquelin” da Technip no Innovation Global Contest, em 2013: “YouTube for Engineering”",
    "LANGUAGES": "IDIOMAS",
    "LANG_1": "Português – Nativo",
    "LANG_2": "Inglês – Fluente",
    "LANG_3": "Espanhol – Intermediário Superior"
};
